version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  web:
    image: nginx:latest
    ports:
      - '8086:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db
    networks:
      - app-network
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - db
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data: